//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Enigma.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ENIGMA_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_A                    129
#define IDB_BITMAP_B                    130
#define IDB_BITMAP_C                    131
#define IDB_BITMAP_D                    132
#define IDB_BITMAP_E                    133
#define IDB_BITMAP_F                    134
#define IDB_BITMAP_G                    135
#define IDB_BITMAP_H                    136
#define IDB_BITMAP_I                    137
#define IDB_BITMAP_J                    138
#define IDB_BITMAP_K                    139
#define IDB_BITMAP_L                    140
#define IDB_BITMAP_M                    141
#define IDB_BITMAP_N                    142
#define IDB_BITMAP_O                    143
#define IDB_BITMAP_P                    144
#define IDB_BITMAP_Q                    145
#define IDB_BITMAP_R                    146
#define IDB_BITMAP_S                    147
#define IDB_BITMAP_T                    148
#define IDB_BITMAP_U                    149
#define IDB_BITMAP_V                    150
#define IDB_BITMAP_W                    151
#define IDB_BITMAP_X                    152
#define IDB_BITMAP_Y                    153
#define IDB_BITMAP_Z                    154
#define IDB_BITMAP_A1                   155
#define IDB_BITMAP_B1                   156
#define IDB_BITMAP_C1                   157
#define IDB_BITMAP_D1                   158
#define IDB_BITMAP_E1                   159
#define IDB_BITMAP_F1                   160
#define IDB_BITMAP_G1                   161
#define IDB_BITMAP_H1                   162
#define IDB_BITMAP_I1                   163
#define IDB_BITMAP_J1                   164
#define IDB_BITMAP_K1                   165
#define IDB_BITMAP_L1                   166
#define IDB_BITMAP_M1                   167
#define IDB_BITMAP_N1                   168
#define IDB_BITMAP_O1                   169
#define IDB_BITMAP_P1                   170
#define IDB_BITMAP_Q1                   171
#define IDB_BITMAP_R1                   172
#define IDB_BITMAP_S1                   173
#define IDB_BITMAP_T1                   174
#define IDB_BITMAP_V1                   175
#define IDB_BITMAP_W1                   176
#define IDB_BITMAP_X1                   177
#define IDB_BITMAP_Y1                   178
#define IDB_BITMAP_Z1                   179
#define IDB_BITMAP_U1                   180
#define IDB_BITMAP_MAIN                 181
#define IDC_TAB1                        1000
#define IDC_BUTTON_A                    1001
#define IDC_BUTTON_B                    1002
#define IDC_BUTTON_C                    1003
#define IDC_BUTTON_D                    1004
#define IDC_BUTTON_E                    1005
#define IDC_BUTTON_F                    1006
#define IDC_BUTTON_G                    1007
#define IDC_BUTTON_H                    1008
#define IDC_BUTTON_I                    1009
#define IDC_BUTTON_J                    1010
#define IDC_BUTTON_K                    1011
#define IDC_BUTTON_L                    1012
#define IDC_BUTTON_M                    1013
#define IDC_BUTTON_N                    1014
#define IDC_BUTTON_O                    1015
#define IDC_BUTTON_P                    1016
#define IDC_BUTTON_Q                    1017
#define IDC_BUTTON_R                    1018
#define IDC_BUTTON_S                    1019
#define IDC_BUTTON_T                    1020
#define IDC_BUTTON_U                    1021
#define IDC_BUTTON_V                    1022
#define IDC_BUTTON_W                    1023
#define IDC_BUTTON_X                    1024
#define IDC_BUTTON_Y                    1025
#define IDC_BUTTON_Z                    1026
#define IDC_STATIC_A                    1029
#define IDC_STATIC_B                    1030
#define IDC_STATIC_C                    1031
#define IDC_STATIC_D                    1032
#define IDC_STATIC_E                    1033
#define IDC_STATIC_F                    1034
#define IDC_STATIC_G                    1035
#define IDC_STATIC_H                    1036
#define IDC_STATIC_I                    1037
#define IDC_STATIC_J                    1038
#define IDC_STATIC_K                    1039
#define IDC_STATIC_L                    1040
#define IDC_STATIC_M                    1041
#define IDC_STATIC_N                    1042
#define IDC_STATIC_O                    1043
#define IDC_STATIC_P                    1044
#define IDC_STATIC_Q                    1045
#define IDC_STATIC_R                    1046
#define IDC_STATIC_S                    1047
#define IDC_STATIC_T                    1048
#define IDC_STATIC_U                    1049
#define IDC_STATIC_V                    1050
#define IDC_STATIC_W                    1051
#define IDC_STATIC_X                    1052
#define IDC_STATIC_Y                    1053
#define IDC_STATIC_Z                    1054
#define IDC_STATIC_A2                   1055
#define IDC_STATIC_B2                   1056
#define IDC_STATIC_C2                   1057
#define IDC_STATIC_D2                   1058
#define IDC_STATIC_E2                   1059
#define IDC_STATIC_F2                   1060
#define IDC_STATIC_G2                   1061
#define IDC_STATIC_H2                   1062
#define IDC_STATIC_I2                   1063
#define IDC_STATIC_J2                   1064
#define IDC_STATIC_K2                   1065
#define IDC_STATIC_L2                   1066
#define IDC_STATIC_M2                   1067
#define IDC_STATIC_N2                   1068
#define IDC_STATIC_O2                   1069
#define IDC_STATIC_P2                   1070
#define IDC_STATIC_Q2                   1071
#define IDC_STATIC_R2                   1072
#define IDC_STATIC_S2                   1073
#define IDC_STATIC_T2                   1074
#define IDC_STATIC_U2                   1075
#define IDC_STATIC_V2                   1076
#define IDC_STATIC_W2                   1077
#define IDC_STATIC_X2                   1078
#define IDC_STATIC_Y2                   1079
#define IDC_STATIC_Z2                   1080
#define IDC_EDIT_INPUT                  1081
#define IDC_EDIT_OUTPUT                 1082
#define IDC_STATIC_INPUT                1083
#define IDC_STATIC_OUTPUT               1084
#define IDC_STATIC_MAIN                 1085
#define IDC_LIST1                       1086
#define IDC_EDIT_ROT1                   1087
#define IDC_EDIT_ROT2                   1088
#define IDC_EDIT_ROT3                   1089
#define IDC_STATIC_ROT1                 1090
#define IDC_STATIC_ROT2                 1091
#define IDC_STATIC_ROT3                 1092
#define IDC_EDIT_RSET                   1093
#define IDC_EDIT_PSET                   1094
#define IDC_STATIC_RSET                 1096
#define IDC_STATIC_PSET                 1097
#define IDC_BUTTON_APPLY                1098
#define IDC_BUTTON_PASTE                1099
#define IDC_EDIT_PASTE                  1100
#define IDC_STATIC_PASTE                1101
#define IDC_BUTTON_CLEAR                1102
#define IDC_STATIC_TYPE                 1103
#define IDC_EDIT_TYPE                   1104
#define IDC_EDIT_ROTS1                  1110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
